In [43]:
import numpy as np
import pandas as pd
import datetime as dt
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [44]:
household_df_reorder = pd.read_csv("../data/processed/household_demographics.csv")

In [45]:
appliances = pd.read_csv("../data/processed1/appliances.csv")

In [46]:
processed_selection = pd.read_csv("../data/processed1/processed_selection.csv")

In [47]:
household_df_reorder.shape

(10974, 12)

In [48]:
household_df_reorder.head(12)

,household_ID,survey_date,household_size,avg_age,max_age,num_children,num_adults,num_elderly,num_employed,avg_hours_home,dependency_ratio,employment_ratio
0,ID0001,2023-12-09,4,49.75,71,0,4,2,3,139.0,0.500000,0.750000
1,ID0001,2024-09-30,5,40.20,71,1,4,2,3,132.8,0.600000,0.600000
2,ID0001,2024-11-28,5,40.20,71,1,4,2,3,132.8,0.600000,0.600000
3,ID0002,2023-12-09,3,70.00,85,0,3,2,2,112.0,0.666667,0.666667
4,ID0002,2024-10-02,3,70.00,85,0,3,2,2,112.0,0.666667,0.666667
5,ID0002,2024-12-11,3,70.00,85,0,3,2,2,112.0,0.666667,0.666667
6,ID0003,2023-12-09,4,42.50,74,1,3,1,2,117.0,0.500000,0.500000
7,ID0003,2024-10-06,4,42.50,74,1,3,1,2,117.0,0.500000,0.500000
8,ID0003,2025-01-12,4,42.50,74,1,3,1,2,117.0,0.500000,0.500000
9,ID0004,2023-12-09,4,35.50,71,1,3,1,1,114.0,0.500000,0.250000
10,ID0005,2023-12-09,2,67.50,78,0,2,1,1,126.0,0.500000,0.500000
11,ID0005,2024-10-15,2,67.50,78,0,2,1,1,126.0,0.500000,0.500000

In [49]:
appliances.shape

(10830, 16)

In [50]:
appliances.head(12)

,household_ID,Heating_Cooking,wave,Communication_IT,Mobility_Energy,Cooling_Refrigeration,Cleaning_Household,Security_Infrastructure,Entertainment_ICT,Other,survey_date,total_appliances,high_energy_appliances,cooling_ratio,digital_lifestyle,appliance_diversity
0,ID0001,1,1,0,0,2,0,0,5,0,2023-12-09,8,3,0.250000,5,3
1,ID0001,1,2,0,0,2,0,0,1,4,2024-09-30,4,3,0.500000,1,3
2,ID0001,2,3,0,0,2,0,0,1,4,2024-11-28,5,4,0.400000,1,3
3,ID0002,0,1,0,0,2,0,0,2,0,2023-12-09,4,2,0.500000,2,2
4,ID0002,0,2,0,0,2,0,0,1,2,2024-10-02,3,2,0.666667,1,2
5,ID0002,0,3,0,0,4,0,0,1,2,2024-12-11,5,4,0.800000,1,2
6,ID0003,6,1,3,1,2,2,0,5,0,2023-12-09,19,10,0.105263,8,6
7,ID0003,6,2,3,1,2,2,0,2,1,2024-10-06,16,10,0.125000,5,6
8,ID0003,6,3,3,1,2,2,0,4,1,2025-01-12,18,10,0.111111,7,6
9,ID0004,6,1,0,0,2,2,0,6,0,2023-12-09,16,10,0.125000,6,4
10,ID0005,3,1,1,0,3,1,0,3,0,2023-12-09,11,7,0.272727,4,5
11,ID0005,3,2,1,0,2,1,0,1,2,2024-10-15,8,6,0.250000,2,5

In [51]:
processed_selection.shape

(2133713, 7)

In [52]:
processed_selection.head()

,datetime,household_ID,branch,sub_type,date,time,consumption
0,2023-02-01 02:29:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-01,02:29,0.000
1,2023-02-01 06:21:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-01,06:21,0.848
2,2023-02-02 01:20:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-02,01:20,3.979
3,2023-02-02 06:26:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-02,06:26,1.117
4,2023-02-03 01:25:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-03,01:25,4.353

In [53]:
processed_selection.rename(columns={'household_id': 'household_ID'}, inplace=True)

In [54]:
processed_selection.head(12)

,datetime,household_ID,branch,sub_type,date,time,consumption
0,2023-02-01 02:29:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-01,02:29,0.0000
1,2023-02-01 06:21:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-01,06:21,0.8480
2,2023-02-02 01:20:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-02,01:20,3.9790
3,2023-02-02 06:26:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-02,06:26,1.1170
4,2023-02-03 01:25:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-03,01:25,4.3530
5,2023-02-03 06:26:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-03,06:26,1.0710
6,2023-02-04 01:23:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-04,01:23,4.2341
7,2023-02-04 06:27:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-04,06:27,1.0339
8,2023-02-05 01:21:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-05,01:21,3.5880
9,2023-02-05 06:21:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-05,06:21,1.0360
10,2023-02-06 01:21:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-06,01:21,3.4381
11,2023-02-06 06:23:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-06,06:23,1.2189

In [55]:
processed_selection.describe().T

,count,mean,std,min,25%,50%,75%,max
consumption,2133713.0,34.046444,756.136803,0.0,0.399,1.015,2.143,36920.053

In [56]:
appliances = appliances.rename(columns={'survey_date': 'datetime'})

In [57]:
household_df_reorder = household_df_reorder.rename(columns={'survey_date': 'datetime'})

In [58]:
processed_selection['datetime'] = pd.to_datetime(processed_selection['datetime'])
appliances['datetime'] = pd.to_datetime(appliances['datetime'])
household_df_reorder['datetime'] = pd.to_datetime(household_df_reorder['datetime'])

In [59]:
processed_selection = processed_selection.sort_values(['household_ID', 'datetime'])
appliances = appliances.sort_values(['household_ID', 'datetime'])
household_df_reorder = household_df_reorder.sort_values(['household_ID', 'datetime'])

Merge appliances and demographics

In [60]:
survey_features = appliances.merge(
    household_df_reorder,
    on=['household_ID', 'datetime'],
    how='left'
)

Time aware merge into 6 hour time series

In [61]:
processed_selection['datetime'] = pd.to_datetime(processed_selection['datetime'], errors='coerce')
survey_features['datetime'] = pd.to_datetime(survey_features['datetime'], errors='coerce')

In [62]:
# Drop NaT
processed_selection = processed_selection.dropna(subset=['datetime'])
survey_features = survey_features.dropna(subset=['datetime'])

In [63]:
processed_selection = processed_selection.sort_values(['household_ID', 'datetime'], kind='mergesort')
survey_features = survey_features.sort_values(['household_ID', 'datetime'], kind='mergesort')

In [64]:
processed_selection = processed_selection.sort_values('datetime')
survey_features = survey_features.sort_values('datetime')

In [65]:
processed_selection = processed_selection.reset_index(drop=True)
survey_features = survey_features.reset_index(drop=True)

In [66]:
full_features = pd.merge_asof(
    processed_selection,
    survey_features,
    by='household_ID',
    left_on='datetime',
    right_on='datetime',
    direction='backward'
)

In [67]:
full_features.head(12)

,datetime,household_ID,branch,sub_type,date,time,consumption,Heating_Cooking,wave,Communication_IT,Mobility_Energy,Cooling_Refrigeration,Cleaning_Household,Security_Infrastructure,Entertainment_ICT,Other,total_appliances,high_energy_appliances,cooling_ratio,digital_lifestyle,appliance_diversity,household_size,avg_age,max_age,num_children,num_adults,num_elderly,num_employed,avg_hours_home,dependency_ratio,employment_ratio
0,2023-01-01 00:30:00,ID2075,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-01-01 00:30:00,ID1738,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-01 00:30:00,ID0411,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-01 00:30:00,ID2727,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-01-01 00:30:00,ID2006,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2023-01-01 00:30:00,ID0845,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-01-01 00:30:00,ID0428,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2023-01-01 00:30:00,ID1834,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023-01-01 00:30:00,ID2771,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2023-01-01 00:31:00,ID2003,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2023-01-01 00:32:00,ID2394,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:32,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2023-01-01 00:33:00,ID2981,MORATUWA,Anteleco - DLMS SinglePhase,2023-01-01,00:33,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
full_features.tail(12)

,datetime,household_ID,branch,sub_type,date,time,consumption,Heating_Cooking,wave,Communication_IT,Mobility_Energy,Cooling_Refrigeration,Cleaning_Household,Security_Infrastructure,Entertainment_ICT,Other,total_appliances,high_energy_appliances,cooling_ratio,digital_lifestyle,appliance_diversity,household_size,avg_age,max_age,num_children,num_adults,num_elderly,num_employed,avg_hours_home,dependency_ratio,employment_ratio
2133701,2024-12-31 05:24:00,ID0290,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,05:24,2.4490,2.0,3.0,1.0,0.0,2.0,1.0,0.0,2.0,1.0,8.0,5.0,0.250000,3.0,5.0,1.0,30.000000,30.0,0.0,1.0,0.0,1.0,16.000000,0.000000,1.000000
2133702,2024-12-31 05:36:00,ID1764,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,05:36,4.8030,15.0,3.0,2.0,0.0,4.0,6.0,2.0,9.0,6.0,38.0,25.0,0.105263,11.0,6.0,5.0,54.600000,85.0,0.0,5.0,3.0,3.0,123.200000,0.600000,0.600000
2133703,2024-12-31 10:46:00,ID2581,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,10:46,16.7029,9.0,3.0,2.0,0.0,2.0,4.0,0.0,4.0,4.0,21.0,15.0,0.095238,6.0,5.0,5.0,43.400000,86.0,1.0,4.0,1.0,1.0,150.800000,0.400000,0.200000
2133704,2024-12-31 13:15:00,ID0938,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:15,10.2731,12.0,3.0,4.0,0.0,3.0,1.0,5.0,7.0,4.0,32.0,16.0,0.093750,11.0,6.0,3.0,23.666667,33.0,1.0,2.0,0.0,2.0,122.000000,0.333333,0.666667
2133705,2024-12-31 13:16:00,ID1197,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:16,8.3210,7.0,1.0,2.0,0.0,2.0,3.0,2.0,7.0,0.0,23.0,12.0,0.086957,9.0,6.0,4.0,29.250000,48.0,2.0,2.0,0.0,1.0,139.250000,0.500000,0.250000
2133706,2024-12-31 13:16:00,ID0579,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:16,1.7970,10.0,3.0,2.0,0.0,3.0,3.0,1.0,5.0,4.0,24.0,16.0,0.125000,7.0,6.0,3.0,43.000000,57.0,0.0,3.0,0.0,2.0,142.333333,0.000000,0.666667
2133707,2024-12-31 13:20:00,ID0875,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:20,1.7811,4.0,1.0,2.0,1.0,2.0,3.0,0.0,3.0,0.0,15.0,9.0,0.133333,5.0,6.0,1.0,47.000000,47.0,0.0,1.0,0.0,1.0,63.000000,0.000000,1.000000
2133708,2024-12-31 13:33:00,ID1054,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:33,11.4751,11.0,3.0,5.0,0.0,2.0,4.0,4.0,10.0,5.0,36.0,17.0,0.055556,15.0,6.0,4.0,35.500000,52.0,1.0,3.0,0.0,2.0,138.000000,0.250000,0.500000
2133709,2024-12-31 13:36:00,ID0940,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:36,16.2340,3.0,1.0,2.0,0.0,2.0,1.0,0.0,3.0,0.0,11.0,6.0,0.181818,5.0,5.0,3.0,49.666667,63.0,0.0,3.0,2.0,1.0,142.333333,0.666667,0.333333
2133710,2024-12-31 13:57:00,ID0246,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,13:57,6.4450,9.0,1.0,3.0,0.0,2.0,5.0,2.0,10.0,1.0,31.0,16.0,0.064516,13.0,6.0,5.0,55.600000,64.0,0.0,5.0,2.0,4.0,100.800000,0.400000,0.800000
2133711,2024-12-31 17:21:00,ID3807,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,17:21,4.0851,3.0,3.0,0.0,0.0,2.0,1.0,0.0,0.0,3.0,6.0,6.0,0.333333,0.0,3.0,4.0,34.000000,54.0,2.0,2.0,0.0,1.0,152.250000,0.500000,0.250000
2133712,2024-12-31 18:36:00,ID3627,NUGEGODA,Anteleco - DLMS SinglePhase,2024-12-31,18:36,0.0000,4.0,3.0,1.0,0.0,2.0,3.0,0.0,3.0,4.0,13.0,9.0,0.153846,4.0,5.0,2.0,71.000000,73.0,0.0,2.0,2.0,0.0,156.000000,1.000000,0.000000

In [69]:
full_features.to_csv("../data/processed1/final_selection.csv", index=False)

In [70]:
full_survey = full_features.copy()

In [71]:
full_survey = full_survey.sort_values(['household_ID','datetime'])

In [72]:
full_survey.head()

,datetime,household_ID,branch,sub_type,date,time,consumption,Heating_Cooking,wave,Communication_IT,Mobility_Energy,Cooling_Refrigeration,Cleaning_Household,Security_Infrastructure,Entertainment_ICT,Other,total_appliances,high_energy_appliances,cooling_ratio,digital_lifestyle,appliance_diversity,household_size,avg_age,max_age,num_children,num_adults,num_elderly,num_employed,avg_hours_home,dependency_ratio,employment_ratio
69876,2023-02-01 02:29:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-01,02:29,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70707,2023-02-01 06:21:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-01,06:21,0.848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71995,2023-02-02 01:20:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-02,01:20,3.979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73371,2023-02-02 06:26:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-02,06:26,1.117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74743,2023-02-03 01:25:00,ID0013,NUGEGODA,Anteleco - DLMS SinglePhase,2023-02-03,01:25,4.353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
full_survey.shape

(2133713, 31)

In [74]:
survey_cols = [											
    'total_appliances',
    'high_energy_appliances',
    'Heating_Cooking',
    'Cooling_Refrigeration',
    'Security_Infrastructure',
    'Cleaning_Household',
    'Entertainment_ICT',
    'Communication_IT',
    'Mobility_Energy',
    'Other',
    'cooling_ratio',
    'digital_lifestyle',
    'appliance_diversity',
    'household_size',
    'avg_age',
    'max_age',
    'num_children',
    'num_adults',
    'num_elderly',
    'num_employed',
    'avg_hours_home',
    'dependency_ratio',
    'employment_ratio'
]

full_survey[survey_cols] = (
    full_survey
    .groupby('household_ID')[survey_cols]
    .ffill()
)

In [75]:
full_survey['valid_start'] = (
    full_survey
    .groupby('household_ID')['total_appliances']
    .transform(lambda x: x.notna().cumsum() > 0)
)

In [76]:
full_survey = full_survey[full_survey['valid_start']].copy()

In [77]:
full_survey.drop(columns=['valid_start'], inplace=True)

In [78]:
full_survey.groupby('household_ID')['datetime'].diff().dropna().value_counts().head()

datetime
1 days 00:00:00    20327
0 days 05:00:00    17679
0 days 23:59:00    16265
1 days 00:01:00    16021
0 days 04:59:00    14606
Name: count, dtype: int64

In [79]:
full_survey.groupby('household_ID').agg(
    start=('datetime', 'min'),
    end=('datetime', 'max'),
    count=('datetime', 'size')
).describe()

,start,end,count
count,1374,1374,1374.000000
mean,2024-03-31 12:50:55.720524032,2024-11-06 04:26:09.519650560,349.537118
min,2023-12-09 01:05:00,2024-02-06 05:58:00,3.000000
25%,2024-01-18 00:47:00,2024-10-31 01:19:00,133.000000
50%,2024-01-26 00:33:00,2024-10-31 01:25:00,453.500000
75%,2024-08-03 01:24:30,2024-10-31 01:39:00,483.000000
max,2024-10-06 01:34:00,2024-12-31 18:36:00,1143.000000
std,NaN,NaN,185.842390

#### Valid Households

Handle households which may start very late which could be useless when modelling

In [80]:
min_points = 100 

valid_households = (
    full_survey
    .groupby('household_ID')
    .filter(lambda x: len(x) >= min_points)
)

In [81]:
valid_households.shape

(470083, 31)

In [82]:
full_survey.shape

(480264, 31)

In [83]:
valid_households.to_csv("../data/processed1/valid_selection.csv", index=False)